-- Trove staleness flag: at most one row, present when the poller has detected that troves.json
-- has changed since the last reload. Cleared when the user triggers a manual reload.
-- stale_trove_ids is comma-delimited (e.g. "vinyl,favorites").
CREATE TABLE trove_staleness (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    detected_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    stale_trove_ids VARCHAR(4096) NOT NULL
);
