// Trove ids as returned by GET /api/troves on the running app.
const TROVE_ID_LIST = [
  '101domain',
  'afternic',
  'alice-in-wonderland',
  'amazon-Alternate History (Fiction)',
  'amazon-Ancient Hist Ling Classics',
  'amazon-Architecture, Construction',
  'amazon-Art, Drawing',
  'amazon-Arts, Crafts, Drawing',
  'amazon-Astronomy',
  'amazon-Audiobooks',
  'amazon-Authored by Assholes',
  'amazon-Bio, Genetics, Comp Bio',
  'amazon-Board games etc',
  'amazon-Books to read Before You Die selon Powells',
  'amazon-CS - _Unfiled',
  "amazon-CS-Agile, Test, IOC, Autom'n",
  'amazon-Camping, outdoor rec',
  'amazon-Cleaning stuff',
  'amazon-Clothes Shoes',
  'amazon-Collection',
  'amazon-Computational Fin and Betting',
  'amazon-Computers, Office, Travel, Road Warrior',
  'amazon-Cooking and Food (books)',
  'amazon-Costa Rica House',
  'amazon-Do not eat these things',
  'amazon-Food',
  'amazon-Food (not books)',
  'amazon-Foundation reading order (bottom to top; Foundation and Earth though Im not sure where)',
  'amazon-Fringe Academia',
  'amazon-Gadgets Toys Electronics',
  'amazon-Garage, Mancave',
  'amazon-KindleyQ',
  'amazon-Kitchen Furniture Home',
  'amazon-Linguistics',
  'amazon-Little Prince',
  'amazon-Maps, Cartography, Geology',
  'amazon-Music',
  'amazon-Photography',
  'amazon-Pol Hist Econ Soc Moral',
  'amazon-Pop Nonfiction',
  'amazon-Pop Tech, Math, Physics, CS',
  'amazon-Prep',
  'amazon-Puzzles, recreational-competitive programming',
  'amazon-Sci Fi Fantasy',
  'amazon-Seasonal',
  'amazon-Seasonal Holiday gear',
  'amazon-Shaving',
  'amazon-Social Networks',
  'amazon-Stats',
  'amazon-The Art of Computer Programming',
  'amazon-Toiletries, Bath, Pills, Pharmacy, Med',
  'amazon-Tolkienism',
  'amazon-Toys, Recreation, Travel',
  'amazon-Translations',
  'amazon-Travel, Foreign Lang',
  'amazon-Vertical messenger bags',
  'amazon-Video - Computer Games (not books)',
  'amazon-Videos DVDs Movies',
  'amazon-Weights Proposal',
  'amazon-Wooden Books',
  'amazon-Writing and Literature',
  'amazon-_Unfiled',
  'audible',
  'books',
  'cafedvd-queue',
  'cloudflare',
  'cocktails',
  'domains',
  'dvdinbox',
  'dvds',
  'fav-sci-fi',
  'fav-series',
  'fav-video-games',
  'foreign-language-books',
  'github',
  'goodreads',
  'gumroad',
  'hard-to-get',
  'hobbit',
  'house-projects',
  'imdb-apocalypse',
  'imdb-christmas',
  'imdb-favorites',
  'imdb-food',
  'imdb-halloween',
  'imdb-hard-to-find',
  'imdb-heavy-hitters',
  'imdb-italian-scifi',
  'imdb-music-biopics',
  'imdb-nsfw',
  'imdb-out-there',
  'imdb-overflow',
  'imdb-rock-operas',
  'imdb-rotoscoping',
  'imdb-schlock',
  'imdb-thanksgiving',
  'imdb-watchlist',
  'isnic',
  'kai-imdb-titles',
  'kai-movies',
  'kai-series',
  'kanopy',
  'kindle',
  'kitchen-gadgets',
  'language-lessons-audio',
  'little-prince',
  'little-prince-duplicates',
  'little-prince-wanted',
  'lost-movies',
  'ls-curated-Books',
  'ls-pdfs',
  'manning',
  'media-personalities',
  'meds',
  'movieq',
  'music',
  'namecheap',
  'netflix-history-carl',
  'netflix-history-cata',
  'netflix-history-condo',
  'netflix-history-kai',
  'netflix-history-pink',
  'netflix-queue',
  'netflix-saved',
  'oreilly',
  'perlego-reading',
  'piquisite',
  'places',
  'podcasts',
  'porkbun',
  'pragprog',
  'productivity-note-apps',
  'purchases',
  'restaurants',
  'screening-list',
  'spotify',
  'synology-courses',
  'synology-documentaries',
  'synology-ebooks',
  'synology-movies',
  'synology-music-videos',
  'synology-nsfw',
  'synology-originals',
  'synology-other-videos',
  'synology-series',
  'test-movies',
  'thorium-reactors',
  'tintenfass-little-prince',
  'trails',
  'travel-wishlist',
  'vinyl'
] as const

export const TROVES: ReadonlySet<TroveId> = new Set(TROVE_ID_LIST)

type TroveId = (typeof TROVE_ID_LIST)[number]

// Hardwired per-trove default thumbnails, used as a fallback in list/gallery view
// when an item has no thumbnail of its own. Keyed by trove id (stable identifier
// used throughout the app), not trove name.
const ICON = {
  audiobooks: '/audioboon-icon.png',
  book: '/book.svg',
  ebook: '/icon-ebook.png',
  filmClapperboard: '/icons/troves/film-clapperboard.svg',
  globe: '/icons/troves/globe.svg',
  goodreads: '/goodreads-logo-mark-circular-28283.svg',
  imdbLogo: '/png-transparent-imdb-icon.png',
  inkwell: '/icons/troves/inkwell.svg',
  kanopyLogo: '/kanopy2-icon.png',
  kindle: '/kindle-icon-2.png',
  languageLessons: '/language-lessons-icon.png',
  musicNote: '/icons/troves/music-note.svg',
  netflix: '/netflix-icon.png',
  opticalDisk: '/optical-disk-icon.png',
  pdf: '/pdf.svg',
  podcast: '/podcast-7477531_1280.png',
  redVideoCamera: '/red-video-camera-13707.svg',
  rose: '/icons/troves/rose.svg',
  shoppingBag: '/icons/troves/shopping-bag.svg',
  spotifyLogo: '/spotify-logo-5426.svg',
  star: '/icons/troves/star.svg',
  video: '/video.svg',
  videoCameraRecording: '/video-camera-recording-13718.svg',
  vinylIcon: '/vinyl-icon.png',
} as const

function iconsFor(ids: readonly TroveId[], icon: string): Partial<Record<TroveId, string>> {
  return Object.fromEntries(ids.map((id) => [id, icon]))
}

const IMDB_TROVES = [...TROVES].filter((id) => id.startsWith('imdb-'))
const AMAZON_TROVES = [...TROVES].filter((id) => id.startsWith('amazon-'))

export const TROVE_DEFAULT_THUMBNAIL: Partial<Record<TroveId, string>> = {
  'tintenfass-little-prince': ICON.inkwell,
  spotify: ICON.spotifyLogo,
  namecheap: ICON.globe,
  porkbun: ICON.globe,
  '101domain': ICON.globe,
  kanopy: ICON.kanopyLogo,
  movieq: ICON.redVideoCamera,
  podcasts: ICON.podcast,
  books: ICON.book,
  goodreads: ICON.goodreads,
  kindle: ICON.kindle,
  'little-prince': ICON.rose,
  vinyl: ICON.vinylIcon,
  dvds: ICON.opticalDisk,
  audible: ICON.audiobooks,
  'language-lessons-audio': ICON.languageLessons,
  'netflix-history-carl': ICON.netflix,
  'netflix-history-cata': ICON.netflix,
  'netflix-history-condo': ICON.netflix,
  'netflix-history-kai': ICON.netflix,
  'netflix-history-pink': ICON.netflix,
  'netflix-queue': ICON.netflix,
  'netflix-saved': ICON.netflix,
  'kai-imdb-titles': ICON.redVideoCamera,
  'kai-movies': ICON.redVideoCamera,
  'cafedvd-queue': ICON.redVideoCamera,
  dvdinbox: ICON.redVideoCamera,
  'lost-movies': ICON.redVideoCamera,
  ...iconsFor(IMDB_TROVES, ICON.imdbLogo),
  ...iconsFor(AMAZON_TROVES, ICON.shoppingBag),
  'fav-series': ICON.filmClapperboard,
  'kai-series': ICON.filmClapperboard,
  'synology-courses': ICON.videoCameraRecording,
  'synology-documentaries': ICON.videoCameraRecording,
  // 'synology-ebooks': ICON.ebook,
  'ls-pdfs': ICON.pdf,
  'ls-curated-Books': ICON.ebook,
  'synology-movies': ICON.videoCameraRecording,
  'synology-music-videos': ICON.videoCameraRecording,
  'synology-nsfw': ICON.videoCameraRecording,
  'synology-originals': ICON.videoCameraRecording,
  'synology-other-videos': ICON.videoCameraRecording,
  'synology-series': ICON.filmClapperboard,
  'music': ICON.musicNote,
  manning: ICON.book,
  afternic: ICON.globe
}
